apiVersion: v1
kind: LimitRange
metadata:
  name: vprofile-limits
  namespace: vprofile
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "2000m"
      memory: 2Gi
    min:
      cpu: "100m"
      memory: "64Mi"
    type: Container
  - max:
      storage: 10Gi
    type: PersistentVolumeClaim
