apiVersion: v1
kind: ResourceQuota
metadata:
  name: vprofile-quota
  namespace: vprofile
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    pods: "10"
    services: "10"
